import { Portfolio, Strategy, Trade } from './types';

export const INITIAL_PORTFOLIO: Portfolio = {
  id: 'portfolio-demo-1',
  name: 'Main Swing & Day Trading',
  initial_balance: 10000,
  currency: 'USD',
  description: 'พอร์ตหลักสำหรับเทรด Forex, Crypto และสินค้าโภคภัณฑ์',
  created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
};

export const INITIAL_STRATEGIES: Strategy[] = [
  {
    id: 'strat-1',
    portfolio_id: 'portfolio-demo-1',
    name: 'Order Block & FVG (SMC)',
    description: 'เข้าเทรดเมื่อราคากลับมา Retest Fair Value Gap และเกิด Choch',
    color: '#6366f1',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'strat-2',
    portfolio_id: 'portfolio-demo-1',
    name: 'Breakout & Retest',
    description: 'เบรคแนวรับ-แนวต้านสำคัญในไทม์เฟรม 1H/4H พร้อม Volume สนับสนุน',
    color: '#10b981',
    created_at: new Date(Date.now() - 28 * 86400000).toISOString(),
  },
  {
    id: 'strat-3',
    portfolio_id: 'portfolio-demo-1',
    name: 'Trend Following (EMA 20/50)',
    description: 'ตามเทรนด์ใหญ่เมื่อราคาย่อตัวหาเส้น EMA 20 บนกราฟ 15M/1H',
    color: '#f59e0b',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'strat-4',
    portfolio_id: 'portfolio-demo-1',
    name: 'Liquidity Sweep Reversal',
    description: 'รอราคา Sweep High/Low วันก่อนหน้าแล้วเกิดสัญญาณกลับตัว Divergence',
    color: '#ec4899',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
];

export const INITIAL_TRADES: Trade[] = [
  {
    id: 'trade-1',
    portfolio_id: 'portfolio-demo-1',
    asset: 'XAUUSD',
    side: 'long',
    entry_price: 2635.50,
    sl: 2628.00,
    tp: 2658.00,
    exit_price: 2655.20,
    size: 1.5,
    fee: 4.50,
    entry_time: new Date(Date.now() - 22 * 86400000).toISOString(),
    exit_time: new Date(Date.now() - 21 * 86400000).toISOString(),
    strategy_id: 'strat-1',
    emotion_tag: 'Disciplined',
    notes: 'ราคาทองคำทำ Sweep Asian Low แล้วเกิด Bullish Engulfing + 15M FVG',
    lessons_learned: 'การรอ Confirm สัญญาณปิดแท่ง 15m ให้ผลลัพธ์ที่คมมาก ไม่ต้องรีบเข้า',
    status: 'closed',
    pnl: 295.50,
    pnl_percentage: 0.75,
    r_multiple: 2.63,
    images: [
      {
        id: 'img-1-1',
        trade_id: 'trade-1',
        image_url: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1200&q=80',
        type: 'setup',
        caption: 'Setup Entry at 15M FVG Bullish Reversal',
        uploaded_at: new Date(Date.now() - 22 * 86400000).toISOString()
      },
      {
        id: 'img-1-2',
        trade_id: 'trade-1',
        image_url: 'https://images.unsplash.com/photo-1642543492481-44e81e3914a7?auto=format&fit=crop&w=1200&q=80',
        type: 'result',
        caption: 'TP reached smoothly before US session close',
        uploaded_at: new Date(Date.now() - 21 * 86400000).toISOString()
      }
    ],
    created_at: new Date(Date.now() - 22 * 86400000).toISOString(),
  },
  {
    id: 'trade-2',
    portfolio_id: 'portfolio-demo-1',
    asset: 'EURUSD',
    side: 'short',
    entry_price: 1.0580,
    sl: 1.0610,
    tp: 1.0490,
    exit_price: 1.0505,
    size: 2.0,
    fee: 6.00,
    entry_time: new Date(Date.now() - 18 * 86400000).toISOString(),
    exit_time: new Date(Date.now() - 17 * 86400000).toISOString(),
    strategy_id: 'strat-3',
    emotion_tag: 'Patient',
    notes: 'หลุดแนวรับเทรนด์ไลน์ 4H แล้วย่อทดสอบ EMA 20 สวยงาม',
    lessons_learned: 'ปล่อยให้กำไรวิ่ง (Let profits run) ตามแผน ช่วยให้ R:R สูงขึ้นชัดเจน',
    status: 'closed',
    pnl: 144.00,
    pnl_percentage: 0.71,
    r_multiple: 2.50,
    images: [
      {
        id: 'img-2-1',
        trade_id: 'trade-2',
        image_url: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1200&q=80',
        type: 'setup',
        caption: 'EURUSD 4H Rejection & Trendline breakdown',
        uploaded_at: new Date(Date.now() - 18 * 86400000).toISOString()
      }
    ],
    created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
  },
  {
    id: 'trade-3',
    portfolio_id: 'portfolio-demo-1',
    asset: 'BTCUSDT',
    side: 'long',
    entry_price: 94200,
    sl: 92800,
    tp: 98500,
    exit_price: 92650,
    size: 0.1,
    fee: 12.00,
    entry_time: new Date(Date.now() - 14 * 86400000).toISOString(),
    exit_time: new Date(Date.now() - 13 * 86400000).toISOString(),
    strategy_id: 'strat-2',
    emotion_tag: 'FOMO',
    notes: 'ไล่ราคาตอนข่าวออก คิดว่าทะลุแนวต้าน 95k',
    lessons_learned: 'อย่าเทรดไล่ราคาตอนข่าวออกเด็ดขาด ควรตั้ง Limit รอให้ราคาย่อตัวก่อน',
    status: 'closed',
    pnl: -167.00,
    pnl_percentage: -1.65,
    r_multiple: -1.11,
    images: [
      {
        id: 'img-3-1',
        trade_id: 'trade-3',
        image_url: 'https://images.unsplash.com/photo-1621416894569-0f39ed31d247?auto=format&fit=crop&w=1200&q=80',
        type: 'setup',
        caption: 'Fake breakout at 95k resistance',
        uploaded_at: new Date(Date.now() - 14 * 86400000).toISOString()
      }
    ],
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'trade-4',
    portfolio_id: 'portfolio-demo-1',
    asset: 'GBPUSD',
    side: 'short',
    entry_price: 1.2640,
    sl: 1.2685,
    tp: 1.2520,
    exit_price: 1.2530,
    size: 2.5,
    fee: 8.00,
    entry_time: new Date(Date.now() - 9 * 86400000).toISOString(),
    exit_time: new Date(Date.now() - 8 * 86400000).toISOString(),
    strategy_id: 'strat-1',
    emotion_tag: 'Confident',
    notes: 'London Session Sweep High แล้วเกิด Bearish FVG ชัดเจนมาก',
    lessons_learned: 'การเข้าตามช่วงเวลา Session สำคัญ (London Open) ได้ความแม่นยำสูง',
    status: 'closed',
    pnl: 267.00,
    pnl_percentage: 0.87,
    r_multiple: 2.44,
    images: [],
    created_at: new Date(Date.now() - 9 * 86400000).toISOString(),
  },
  {
    id: 'trade-5',
    portfolio_id: 'portfolio-demo-1',
    asset: 'NVDA',
    side: 'long',
    entry_price: 138.50,
    sl: 134.00,
    tp: 152.00,
    exit_price: 147.20,
    size: 30,
    fee: 3.50,
    entry_time: new Date(Date.now() - 5 * 86400000).toISOString(),
    exit_time: new Date(Date.now() - 4 * 86400000).toISOString(),
    strategy_id: 'strat-2',
    emotion_tag: 'Disciplined',
    notes: 'หุ้น AI ยก High ยก Low บน Daily Chart ทะลุ Flag Pattern',
    lessons_learned: 'Trailing Stop ตามจุด Swing Low ช่วยล็อกกำไรได้ดีเมื่อชนเป้าหลัก',
    status: 'closed',
    pnl: 257.50,
    pnl_percentage: 6.28,
    r_multiple: 1.93,
    images: [],
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'trade-6',
    portfolio_id: 'portfolio-demo-1',
    asset: 'XAUUSD',
    side: 'long',
    entry_price: 2680.00,
    sl: 2668.00,
    tp: 2715.00,
    exit_price: undefined,
    size: 1.2,
    fee: 3.60,
    entry_time: new Date(Date.now() - 1 * 86400000).toISOString(),
    exit_time: undefined,
    strategy_id: 'strat-1',
    emotion_tag: 'Confident',
    notes: 'ราคาทองรีเทสต์ 4H Order Block แข็งแกร่ง กำลังมีแรงซื้อดันกลับ',
    lessons_learned: undefined,
    status: 'open',
    pnl: 0,
    pnl_percentage: 0,
    r_multiple: 0,
    images: [
      {
        id: 'img-6-1',
        trade_id: 'trade-6',
        image_url: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1200&q=80',
        type: 'setup',
        caption: '4H Order Block Bullish Defense Zone',
        uploaded_at: new Date(Date.now() - 1 * 86400000).toISOString()
      }
    ],
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'trade-7',
    portfolio_id: 'portfolio-demo-1',
    asset: 'ETHUSDT',
    side: 'short',
    entry_price: 2750.00,
    sl: 2820.00,
    tp: 2580.00,
    exit_price: undefined,
    size: 2.0,
    fee: 4.00,
    entry_time: new Date(Date.now() - 8 * 3600000).toISOString(),
    exit_time: undefined,
    strategy_id: 'strat-4',
    emotion_tag: 'Patient',
    notes: 'เกิด Bearish Divergence ที่แนวต้าน $2,800 + หลุดเส้น neckline 1H',
    lessons_learned: undefined,
    status: 'open',
    pnl: 0,
    pnl_percentage: 0,
    r_multiple: 0,
    images: [],
    created_at: new Date(Date.now() - 8 * 3600000).toISOString(),
  },
];
